name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['debian:10', 'debian:11', 'ubuntu:18.04', 'ubuntu:20.04', 'ubuntu:22.04']
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Install build essentials
      run: |
        apt-get -y update
        apt-get -y install build-essential

    - name: Build all disabled
      run: |
       ./configure --disable-linuxdvb --disable-dvbca --disable-dvbcsa --disable-netcv --disable-satipc --disable-dvbapi
       make

    - name: Install additional build dependencies
      run: |
        apt-get -y install libdvbcsa-dev libssl-dev

    - name: Build all enabled
      run: |
       make clean
       ./configure --enable-linuxdvb --enable-dvbca --enable-dvbcsa --enable-netcv --enable-satipc --enable-dvbapi --enable-axe
       make

    - name: Build with --enable-axe, without libssl-dev
      run: |
       apt-get -y remove --purge libssl-dev
       make clean
       ./configure --enable-axe --enable-dvbapi --enable-dvbcsa --disable-dvbca --disable-dvbaes --disable-netcv
       make
